services:
  service-name:
    image: postgres:10.5-alpine
    container_name: service-name
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=localhost
      - DB_DBNAME=postgres
      - DB_PORT=5432
    ports:
      - '5432:5432'
    networks:
      - service-network
networks:
  service-network:
    external: true